{{- range $svc := list "producer" "consumer" }}
{{- $app := index $.Values.apps $svc }}
{{- if $app.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.tenantId }}-{{ $svc }}
  namespace: {{ $.Values.tenantId }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ $.Values.accountId }}:role/{{ $svc }}-role-{{ $.Values.tenantId }}
---
{{- end }}
{{- end }}
